spring:
  application:
    name: LeaveRestApplication
  # 数据源定义
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leave
  # jpa配置
  jpa:
    hibernate:
      # 更新，启动不会清除数据
      ddl-auto: update
    # 显示sql
    show-sql: true
    generate-ddl: off

# jwt配置
leave:
  properties:
    jwt-rest-time: 2400000
    jwt-time: 3600000
    jwt-secret-key: Q2EDw2xtNINTEu3J5ijluLn2M6HboXpiNbefCKrl
## dubbo 配置
dubbo:
  application:
    name: LeaveRestApplication
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: cn.allms.leave.rpc